name: Generate Stats Images

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  generate-images:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: jstrieb/github-stats@master
        with:
          username: Anik-Sarkar-01
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
